/**
 * Universal Decompiler E2E Tests
 *
 * Tests for decompiling arbitrary TypeScript code (not generated by flow2code).
 * Covers: function selection, route inference, audit hints, control flow,
 * and validateFlowIR malformed input guard.
 */

import { describe, it, expect } from "vitest";
import { decompile } from "../../src/lib/compiler/decompiler";
import { validateFlowIR } from "../../src/lib/ir/validator";
import { NodeCategory } from "../../src/lib/ir/types";
import type { FlowIR } from "../../src/lib/ir/types";

describe("Universal Decompiler E2E", () => {
    // ────────────────────────────────────────────────────
    // --function flag
    // ────────────────────────────────────────────────────

    describe("--function flag", () => {
        const multiHandlerCode = `
import { NextRequest, NextResponse } from "next/server";

export async function GET(req: NextRequest) {
  return NextResponse.json({ method: "GET" });
}

export async function POST(req: NextRequest) {
  const body = await req.json();
  return NextResponse.json({ method: "POST", body }, { status: 201 });
}

export async function DELETE(req: NextRequest) {
  return NextResponse.json({ method: "DELETE" }, { status: 204 });
}
`;

        it("should select POST when --function POST is specified", () => {
            const result = decompile(multiHandlerCode, { functionName: "POST" });
            expect(result.success).toBe(true);

            const trigger = result.ir!.nodes.find((n) => n.category === NodeCategory.TRIGGER);
            expect(trigger).toBeDefined();
            expect((trigger!.params as any).method).toBe("POST");
        });

        it("should select DELETE when --function DELETE is specified", () => {
            const result = decompile(multiHandlerCode, { functionName: "DELETE" });
            expect(result.success).toBe(true);

            const trigger = result.ir!.nodes.find((n) => n.category === NodeCategory.TRIGGER);
            expect((trigger!.params as any).method).toBe("DELETE");
        });

        it("should default to GET (first HTTP method) when no --function flag", () => {
            const result = decompile(multiHandlerCode);
            expect(result.success).toBe(true);

            const trigger = result.ir!.nodes.find((n) => n.category === NodeCategory.TRIGGER);
            expect((trigger!.params as any).method).toBe("GET");
        });
    });

    // ────────────────────────────────────────────────────
    // Route path inference
    // ────────────────────────────────────────────────────

    describe("Route path inference", () => {
        const simpleHandler = `
import { NextResponse } from "next/server";
export async function GET() {
  return NextResponse.json({ ok: true });
}
`;

        it("should infer /api/hello from app/api/hello/route.ts", () => {
            const result = decompile(simpleHandler, {
                fileName: "/project/src/app/api/hello/route.ts",
            });
            expect(result.success).toBe(true);

            const trigger = result.ir!.nodes.find((n) => n.category === NodeCategory.TRIGGER);
            expect((trigger!.params as any).routePath).toBe("/api/hello");
        });

        it("should infer /api/users from app/api/users/route.ts", () => {
            const result = decompile(simpleHandler, {
                fileName: "/home/user/myapp/app/api/users/route.ts",
            });
            expect(result.success).toBe(true);

            const trigger = result.ir!.nodes.find((n) => n.category === NodeCategory.TRIGGER);
            expect((trigger!.params as any).routePath).toBe("/api/users");
        });

        it("should use /api/handler as fallback for non-standard paths", () => {
            const result = decompile(simpleHandler, { fileName: "handler.ts" });
            expect(result.success).toBe(true);

            const trigger = result.ir!.nodes.find((n) => n.category === NodeCategory.TRIGGER);
            // Should have some route path, even if fallback
            expect((trigger!.params as any).routePath).toBeDefined();
        });
    });

    // ────────────────────────────────────────────────────
    // Audit hints
    // ────────────────────────────────────────────────────

    describe("Audit hints", () => {
        it("should detect fetch without try/catch", () => {
            const code = `
export async function GET() {
  const resp = await fetch("https://api.example.com/data");
  const data = await resp.json();
  return Response.json(data);
}
`;
            const result = decompile(code, { audit: true });
            expect(result.success).toBe(true);
            expect(result.audit).toBeDefined();
            expect(result.audit!.length).toBeGreaterThan(0);

            // Should have a warning about missing error handling
            const missingTryCatch = result.audit!.find((h) =>
                h.message.includes("no error handling") || h.message.includes("try/catch")
            );
            expect(missingTryCatch).toBeDefined();
        });

        it("should detect fetch without response.ok check", () => {
            const code = `
export async function GET() {
  const resp = await fetch("https://api.example.com/data");
  const data = await resp.json();
  return Response.json(data);
}
`;
            const result = decompile(code, { audit: true });
            expect(result.success).toBe(true);

            const noResponseCheck = result.audit!.find((h) =>
                h.message.includes("response.ok") || h.message.includes("response.status")
            );
            expect(noResponseCheck).toBeDefined();
        });

        it("should not generate audit hints when audit=false", () => {
            const code = `
export async function GET() {
  const resp = await fetch("https://api.example.com/data");
  return Response.json(await resp.json());
}
`;
            const result = decompile(code, { audit: false });
            expect(result.success).toBe(true);
            // audit should be empty or undefined
            expect(result.audit?.length ?? 0).toBe(0);
        });
    });

    // ────────────────────────────────────────────────────
    // Control flow decompilation
    // ────────────────────────────────────────────────────

    describe("Control flow patterns", () => {
        it("should handle try/catch blocks", () => {
            const code = `
export async function GET() {
  try {
    const data = await fetch("https://api.example.com").then(r => r.json());
    return Response.json(data);
  } catch (error) {
    return Response.json({ error: "Failed" }, { status: 500 });
  }
}
`;
            const result = decompile(code);
            expect(result.success).toBe(true);

            const tryCatch = result.ir!.nodes.find((n) => n.nodeType === "try_catch");
            expect(tryCatch).toBeDefined();
        });

        it("should handle for...of loops", () => {
            const code = `
export async function GET() {
  const items = [1, 2, 3];
  const results: number[] = [];
  for (const item of items) {
    results.push(item * 2);
  }
  return Response.json({ results });
}
`;
            const result = decompile(code);
            expect(result.success).toBe(true);

            const loopNode = result.ir!.nodes.find((n) => n.nodeType === "for_loop");
            expect(loopNode).toBeDefined();
        });

        it("should handle if/else with both branches", () => {
            const code = `
export async function POST(req: Request) {
  const body = await req.json();
  if (body.admin) {
    return Response.json({ role: "admin" });
  } else {
    return Response.json({ role: "user" });
  }
}
`;
            const result = decompile(code);
            expect(result.success).toBe(true);

            const ifNode = result.ir!.nodes.find((n) => n.nodeType === "if_else");
            expect(ifNode).toBeDefined();
        });
    });

    // ────────────────────────────────────────────────────
    // validateFlowIR guard
    // ────────────────────────────────────────────────────

    describe("validateFlowIR malformed input", () => {
        it("should return error for empty object {}", () => {
            const result = validateFlowIR({} as FlowIR);
            expect(result.valid).toBe(false);
            expect(result.errors.length).toBeGreaterThan(0);
            expect(result.errors[0].code).toBe("MISSING_NODES");
        });

        it("should return error for null input", () => {
            const result = validateFlowIR(null as any);
            expect(result.valid).toBe(false);
            expect(result.errors[0].code).toBe("INVALID_INPUT");
        });

        it("should return error for undefined input", () => {
            const result = validateFlowIR(undefined as any);
            expect(result.valid).toBe(false);
            expect(result.errors[0].code).toBe("INVALID_INPUT");
        });

        it("should return error when nodes is not an array", () => {
            const result = validateFlowIR({ nodes: "not-array", edges: [] } as any);
            expect(result.valid).toBe(false);
            expect(result.errors[0].code).toBe("MISSING_NODES");
        });

        it("should return error when edges is missing", () => {
            const result = validateFlowIR({ nodes: [] } as any);
            expect(result.valid).toBe(false);
            expect(result.errors[0].code).toBe("MISSING_EDGES");
        });
    });

    // ────────────────────────────────────────────────────
    // Edge cases
    // ────────────────────────────────────────────────────

    describe("Edge cases", () => {
        it("should fail gracefully for non-function code", () => {
            const code = `
const x = 42;
console.log("hello world");
`;
            const result = decompile(code);
            expect(result.success).toBe(false);
        });

        it("should handle arrow function exports", () => {
            const code = `
export const handler = async (req: Request) => {
  return Response.json({ ok: true });
};
`;
            const result = decompile(code);
            expect(result.success).toBe(true);
            expect(result.ir!.nodes.length).toBeGreaterThanOrEqual(1);
        });

        it("should produce valid FlowIR version", () => {
            const code = `
export async function GET() {
  return Response.json({ ok: true });
}
`;
            const result = decompile(code);
            expect(result.success).toBe(true);
            expect(result.ir!.version).toBe("1.0.0");
            expect(result.ir!.meta).toBeDefined();
            expect(result.ir!.meta.createdAt).toBeDefined();
        });

        it("should track confidence score between 0 and 1", () => {
            const code = `
export async function GET(req: Request) {
  const data = await fetch("https://api.example.com").then(r => r.json());
  return Response.json(data);
}
`;
            const result = decompile(code);
            expect(result.success).toBe(true);
            expect(result.confidence).toBeGreaterThanOrEqual(0);
            expect(result.confidence).toBeLessThanOrEqual(1);
        });
    });
});
